### ISSUE TITLE
Can't build using sphinx-build

### ISSUE THREAD

**Issue by goodlux** [codejamninja/sphinx-jekyll-builder#6]
Trying this for the first time

When I use the sphinx-build command in the docs directory. 
Thanks!

```
sphinx-build -M jekyll ./ _build/jekyll
```

I get the following errors.

```
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 17, in <module>
    from typing import Any, IO, List
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.7/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

```

I've followed the setup as described, not sure what the issue is here. Thanks!

**Comment by goodlux** [comment]
i had better luck using -b in the sphinx-build command! 
sphinx-build -b jekyll ./ _build/jekyll
